name: build flatpak
on:
  - push
  - pull_request
jobs:
  flatpak-build:
    name: flatpak build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flatpak:
          - id: io.github.pocketblue.handyfox
            name: handyfox
          - id: org.mozilla.firefox.systemconfig
            name: firefox-systemconfig
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          echo '${{ secrets.private_gpg }}' | gpg --import
          git clone 'https://github.com/pocketblue/${{ matrix.flatpak.name }}'
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --disable-rofiles-fuse --user --gpg-sign=gmankab@gmail.com --install-deps-from=flathub --repo=repo ./build '${{ matrix.flatpak.name }}/${{ matrix.flatpak.id }}.yml'
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.flatpak.id }}-repo
          path: repo
  push_repo:
    name: push repo
    needs:
      flatpak-build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          echo '${{ secrets.private_gpg }}' | gpg --import
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: write metadata
        run: |
          mkdir ./deploy/repo
          ostree init --mode=archive-z2 --repo ./deploy/repo
          for dir in ./artifacts/* ; do
            mkdir -p $dir/refs/remotes $dir/refs/mirrors
            touch $dir/refs/remotes/.gitkeep $dir/refs/mirrors/.gitkeep
            ostree --repo=./deploy/repo pull-local $dir
          done
          flatpak build-update-repo --gpg-sign=gmankab@gmail.com ./deploy/repo
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true
